# Generated by Django 3.2.9 on 2021-11-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_clone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dislike',
            field=models.IntegerField(max_length=50, null=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.IntegerField(max_length=50, null=0),
        ),
    ]
